use CHATAPPDB;
CREATE TABLE END_USER_DETAILS(USERNAME VARCHAR(20), PASSWORD VARCHAR(20),TYPE VARCHAR(20),
CHECK(TYPE IN ('server','client')),
PRIMARY KEY(USERNAME,TYPE));

CREATE TABLE MESSAGES_HISTORY(USERNAME VARCHAR(20),TYPE VARCHAR(20),SENT VARCHAR(1000),
RECIEVED VARCHAR(1000),TIME TIMESTAMP,
PRIMARY KEY (USERNAME,TYPE,TIME),
FOREIGN KEY (USERNAME,TYPE) REFERENCES END_USER_DETAILS(USERNAME,TYPE)
ON DELETE CASCADE
ON UPDATE CASCADE);

SELECT * FROM END_USER_DETAILS;
SELECT *from MESSAGES_HISTORY;